### ISSUE TITLE
MSFT_SPWebAppSiteUseAndDeletion Weird Issues in Set-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#615] opened 2017-06-09 10:04 UTC
**Details of the scenario you try and problem that is occurring:**
When I try to execute the DSC block provided below, I get the following error:
PowerShell DSC resource MSFT_SPWebAppSiteUseAndDeletion  failed to execute 
Test-TargetResource functionality with error message: Cannot validate argument on 
parameter 'UnusedSiteNotificationsBeforeDeletion'. The 4 argument is less than the minimum 
allowed range of 28. Supply an argument that is greater than or equal to 28 and then try 
the command again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

I then do as told, and change the value of UnusedSiteNotificationsBeforeDeletion to 28, and then I get the following error:
PowerShell DSC resource MSFT_SPWebAppSiteUseAndDeletion  failed to execute 
Set-TargetResource functionality with error message: Exception setting 
"UnusedSiteNotificationsBeforeDeletion": "Specified argument was out of the range of valid 
values.
Parameter name: Number of weekly notifications.  This value must be >= 4 and <= 24" 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**The DSC configuration that is using the resource:**
SPWebAppSiteUseAndDeletion 683caa09-de6c-4b64-b52e-fee1dcf27176
        {
            AutomaticallyDeleteUnusedSiteCollections = $False;
            PsDscRunAsCredential = $Credsdw_spfarm;
            UnusedSiteNotificationsBeforeDeletion = 4;
            SendUnusedSiteCollectionNotifications = $False;
            UnusedSiteNotificationPeriod = 90;
            Url = "http://find-dev2013.nik.net/";
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2k12R2/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**DELETE THIS LINE AND BELOW**

_Your feedback and support is greatly appreciated._

_If you are able to resolve this issue or add new features, you may submit a Pull Request against this project._
_Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

**Comment by ykuijs** [comment] 2017-06-09 15:15
Working on it

**Comment by ykuijs** [comment] 2017-06-09 21:01
Weird thing: When opening these settings via the CA, the default value is 28. When I change it to 4, save it, then reopen it again and try to set the value back to 28, I get the message the value has to be between 4 and 24.

I then opened the same settings for another web application, changed the default value of 28 to 50 and what able to save it. However when trying to change it to a value lower than 28 or higher then 68, I get the message the value has to be between 28 and 68......

I am using SP2013 at the moment. Anybody able to reproduce?

**Comment by NikCharlebois** [comment] 2017-06-09 21:05
Ok, just thought of something. Could it be that that value is mixing days and weeks. 4 weeks is 28 days....could it be related to that in some ways?

**Comment by ykuijs** [comment] 2017-06-13 09:46
Wow, that is a good spot: 4 weeks is 28 days and 24 weeks is 168 days.....so it can be some kind a calculation issue in the CA! Will dive into this!

**Comment by ykuijs** [comment] 2017-06-13 14:17
Just checked the code for SPWebApplication and as it turns out the value of UnusedSiteNotificationsBeforeDeletion depends on the schedule of the dead-site-delete timer job. When this is set to weekly, the range is 4 to 24. If it is set to daily, the range is 28 to 168. If it is set to monthly, the range is 2 to 6.

You can use SPTimerJobState to manage this schedule and then use the correct range.

I will:
-  Add a check to this resource to select the correct range based on the selected schedule and generate logical error messages
-  Update the documentation of the resource

**Comment by ykuijs** [comment] 2017-07-04 12:57
This is fixed in PR630.

**Closed by ykuijs** 2017-07-04 12:57 UTC
Labels: bug, in progress

**Comment by ykuijs** [comment] 2017-07-04 13:00
Linking to PR #630
