### ISSUE TITLE
Using SQL Alias

### ISSUE THREAD

**Issue by cathornton** [PowerShell/SharePointDsc#422] opened 2016-10-10 04:15 UTC
**Details of the scenario you try and problem that is occurring:**
I have been trying to refer to my Database Server using my SQL Alias (set in cliconfg.exe).  It seems that none of my commands work unless I use the actual Database Server name itself.

**The DSC configuration that is using the resource:**
For example: https://github.com/PowerShell/SharePointDsc/wiki/SPWebApplication
When I use DatabaseServer parameter I get "Cannot Find Server" if I use the SQL Alias.  It only works when I use the SQL Server machine name.

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2
Powershell Version 5 (Windows Management Framework 5.0)

**Version of the DSC module you're using:**
Find-Module -Name SharePointDsc -Repository PSGallery | Install-Module

**Comment by MikeLacher448** [comment] 2016-10-10 12:50
I also use SQL alias for my builds, and have not yet run into any issues with any of the DSC resources.
Other then ensuring the SQL alias is set on each SharePoint server, there really isn't anything else to configure. Can you try and perform the same actions without DSC to verify the SQL alias is configured properly?

**Comment by ykuijs** [comment] 2016-10-10 13:27
Agree with Mike, I also use SQL aliases without any issues. I have seen issues in the past with aliases not working properly. Never figured out the cause, but the solution was to create a DNS record for the alias.

**Comment by luigilink** [comment] 2016-10-10 18:13
I had an issue because the "Dynamically determine port" was't checked.
Before installing SP, I always check the SQL connection with a UDL file.

**Comment by BrianFarnhill** [comment] 2016-10-10 22:27
@cathornton Can you try to create the web application through PowerShell directly to test if that works. All the DSC resource does is natively call out to New-SPWebApplication, so you should be able to test it by calling that directly

    New-SPWebApplication -Name "Contoso Internet Site" -URL "https://www.contoso.com" -ApplicationPool "ContosoAppPool" -DatabaseServer "YOUR.ALIAS.HERE" -DatabaseName "WSS_Content"

As per the previous comments, my expectation is that this will show you the same error as the DSC resource is, which will likely relate to how the client alias has been configured.

On SQL aliases in general though, I do not recommend these to my customers as they actually break some of the health analyser rules in SharePoint that attempt to check things at SQL server, as they assume that the alias is the computer name and attempt to connect that way but will then fail as that isn't valid. If you are using aliases to give you the ability to easily move SQL server later on, I would suggest considering using DNS to help route you to an appropriate SQL server as a better alternative. 

Let us know how you go testing the web app creation manually and we'll be able to help more from there.

**Comment by cathornton** [comment] 2016-10-11 03:07
thanks for the feedback everyone. Unfortunately I can no longer replicate this issue.  My test results have been a bit inconsistent so I suspect there may be other issues at play in my environment.

@BrianFarnhill your point on using DNS instead of SQL Alias is a good one and I will take it on board.

**Comment by BrianFarnhill** [comment] 2016-10-11 03:54
@cathornton No worries - hope you work it all out! Closing this issue off.

**Closed by BrianFarnhill** 2016-10-11 03:54 UTC
Labels: Investigating, question
