### ISSUE TITLE
SPJoinFarm Error

### ISSUE THREAD

**Issue by aatighi** [PowerShell/SharePointDsc#381] opened 2016-08-03 23:20 UTC
I am able to join my VM to the Farm using SPJoinFarm for Sharepoint 2013 but at the end it returns the following error:

MSFT_SPJoinFarm  failed to execute Set-TargetResource functionality with error message: ScriptHalted  The SendConfigurationApply function did not succeed

I am using SharePointDSC 1.1.0.0

**Comment by BrianFarnhill** [comment] 2016-08-03 23:23
@aatighi Can you send us the full logs for that part of the resource. That error indicates that there would have been an exception before it somewhere which should tell us what has gone wrong.

**Comment by aatighi** [comment] 2016-08-04 04:18
Hi @BrianFarnhill , Here is the log I am receiving when I run this manually on the box, Interesting part is, as I mentioned, Joining Farm goes through successfully, but still I receive the following error.

PowerShell DSC resource MSFT_SPJoinFarm  failed to execute Set-TargetResource functionality with error message: ScriptHalted 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost



And this is the DSC script that I run.

SPJoinFarm JoinSPFarm
        {
            DatabaseServer           = "$DatabaseServersufx$Slot.$DomainName"
            FarmConfigDatabaseName   = "Config"
            Passphrase               = $Passphrase
            InstallAccount           = $SPsetupUserCreds
            
        }

**Comment by BrianFarnhill** [comment] 2016-08-04 04:22
Can you get me the verbose output from the configuration? When you use Start-DscConfiguration add -Verbose to the command so we can see the full output of whats happening.

**Comment by aatighi** [comment] 2016-08-04 04:36
PS C:\Packages\Plugins\Microsoft.Powershell.DSC\2.20.0.0\DSCWork\SP.ps1.1> Start-DscConfiguration .\Test -Verbose -Force -Wait
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSC
LocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer xxxx with user sid .
VERBOSE: [xxxx]: LCM:  [ Start  Set      ]
VERBOSE: [xxxx]: LCM:  [ Start  Resource ]  [[SPJoinFarm]JoinSPFarm]
VERBOSE: [xxxx]: LCM:  [ Start  Test     ]  [[SPJoinFarm]JoinSPFarm]
VERBOSE: [xxxx]:                            [[SPJoinFarm]JoinSPFarm] Checking for local SP Farm
VERBOSE: [xxxx]:                            [[SPJoinFarm]JoinSPFarm] Executing using a provided credential and local PSSess
ion as user domain\user
VERBOSE: [xxxx]:                            [[SPJoinFarm]JoinSPFarm] Testing for local farm presence
VERBOSE: [xxxx]: LCM:  [ End    Test     ]  [[SPJoinFarm]JoinSPFarm]  in 3.5370 seconds.
VERBOSE: [xxxx]: LCM:  [ Start  Set      ]  [[SPJoinFarm]JoinSPFarm]
VERBOSE: [xxxx3]:                            [[SPJoinFarm]JoinSPFarm] Joining existing farm configuration database
VERBOSE: [xxxx]:                            [[SPJoinFarm]JoinSPFarm] Checking for local SP Farm
VERBOSE: [xxxx]:                            [[SPJoinFarm]JoinSPFarm] Executing using a provided credential and local PSSess
ion as user domain\user
VERBOSE: [xxxx]:                            [[SPJoinFarm]JoinSPFarm] Executing using a provided credential and local PSSess
ion as user domain\user
VERBOSE: [xxxx]:                            [[SPJoinFarm]JoinSPFarm] An error occured joining the farm
VERBOSE: [xxxx]: LCM:  [ End    Set      ]  [[SPJoinFarm]JoinSPFarm]  in 98.9580 seconds.
PowerShell DSC resource MSFT_SPJoinFarm  failed to execute Set-TargetResource functionality with error message: ScriptHalted 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [xxxx]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 102.795 seconds

**Comment by BrianFarnhill** [comment] 2016-08-04 05:04
OK I can see that we aren't throwing that exception up correctly, so it looks like there is an issue that is being hidden from our logs there. I can code up a fix that should show the additional detail. Will get back to you with it when I get a sec.

**Comment by MikeLacher448** [comment] 2016-08-19 16:26
just tried a new deployment in my lab and am getting the same behavior. If I find anything, I'll let you know.

**Comment by MikeLacher448** [comment] 2016-08-23 09:23
this is fixed with pull request #392

**Comment by BrianFarnhill** [comment] 2016-08-24 00:30
Confirmed that this was fixed in #392 and will ship in v1.3 of SharePointDsc - closing this one off, thanks guys.

**Closed by BrianFarnhill** 2016-08-24 00:30 UTC
Labels: bug, in progress
