### ISSUE TITLE
The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by ZeweiS** [PowerShell/SharePointDsc#372] opened 2016-07-13 22:34 UTC
**The DSC configuration that is using the resource:**
            VisioService = @{
                Name = "Visio Service Application"
            }
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2, SharePoint Server 2016

**Version of the DSC module you're using:**
SharePointDsc 1.1.0.0

**Error Message:
PowerShell DSC resource MSFT_SPVisioServiceApp  failed to execute Set-TargetResource functionality with error message:
The term 'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : XXX-01

**Comment by BrianFarnhill** [comment] 2016-07-13 22:36
Thanks for reporting @ZeweiS - we'll investigate and get back to you shortly

**Comment by BrianFarnhill** [comment] 2016-07-15 03:11
@ZeweiS A couple of things here - firstly are you able to provide a copy of the resource from your configuration so I can see the specific settings you have called it with? If not can you at least let me know if you are using PSDscRunAsCredential or the InstallAccount parameter? 

Secondly can you confirm that if you open the SharePoint management shell on the impacted server that you can still manually call New-SPVisioServiceApplication as well

**Comment by ZeweiS** [comment] 2016-07-15 03:33
I will email you the full psd1 file via internal email. And yes, I could call the cmdlet from the server if I launch a SharePoint PS window.

**Comment by NikCharlebois** [comment] 2016-10-04 20:46
@BrianFarnhill assign that one to me as well, I'll do the follow-up

**Comment by BrianFarnhill** [comment] 2016-10-04 20:55
@ykuijs Do you think this one could be related to the bug you found with the content database command not being found as well?

**Comment by ykuijs** [comment] 2016-10-05 13:20
No, unfortunately not. This resource isn't using a module file.

**Comment by ykuijs** [comment] 2016-10-26 11:16
@NikCharlebois Was this also fixed in #411 or is this still under investigation?

**Comment by NikCharlebois** [comment] 2016-10-26 11:40
@ykuijs leave this one open I think. I was never able to replicate the issue on my end. @ZeweiS are you still face with this issue with the latest builds?

**Comment by Mindzweeper** [comment] 2017-03-13 21:40
Can reproduce reliably with the latest version.  Key behavior is:
1) See error reported by ZeweiS when first running DSC.
2) Do not get this error when executing that cmdlet from local SharePoint Management Shell.
3) Service does eventually get created without additional action needed.

**Comment by ykuijs** [comment] 2017-11-03 13:15
Hello @ZeweiS, I just tested the resource on Windows Server 2012 R2 and SP2016 with v1.9 and everything is working just fine. Can you please test the issue with the most recent version once more and let me know if you can reproduce the issue?

I used this config:
`        SPVisioServiceApp Visio
        {
            Name  = "Visio Service App"
            ApplicationPool = "Visio"
            Ensure     = "Present"
            PsDscRunAsCredential = $SPSetupAccount
        }
`

**Comment by NikCharlebois** [comment] 2018-01-17 13:36
I am not able to replicate this on my end either with the latest versions. I recommend closing this issue.

**Comment by ykuijs** [comment] 2018-01-22 21:36
Closing the issue since we can't reproduce the issue and creator hasn't responded to earlier questions.

Please reopen the issue if the issue remains

**Closed by ykuijs** 2018-01-22 21:36 UTC
Labels: Investigating
