### ISSUE TITLE
XspInstallPrereqs Error

### ISSUE THREAD

**Issue by Pherat** [PowerShell/SharePointDsc#401] opened 2016-09-11 09:14 UTC
The configuration that I am running is DSC as a pull server. The issue that I have is an error I get when running Get-DSCConfiguration from the client server. The error is below:

Get-DscConfiguration : The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The
Verbose key is not a valid property in the corresponding DSC resource schema file. The results from Get-TargetResource
must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC
resource schema file.
At line:1 char:1
+ Get-DscConfiguration -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Ge
   t-DscConfiguration], CimException
    + FullyQualifiedErrorId : GetOperationResultInvalidResultFormat,Get-DscConfiguration

The code that it is trying to run is below:

       xSPInstallPrereqs InstallPrerequisites
        {
            Ensure            = "Present" 
            InstallerPath     = "C:\Powerhsell\DSC\Installs\Prerequisiteinstaller.exe"   
            OnlineMode        = $false
            NETFX             = "C:\Powerhsell\DSC\Installs\dotnetfx45_full_x86_x64.exe"
            AppFabric         = "C:\Powerhsell\DSC\Installs\WindowsServerAppFabricSetup_x64.exe"
            IDFX11            = "C:\Powerhsell\DSC\Installs\MicrosoftIdentityExtensions-64.msi"
            MSIPCClient       = "C:\Powerhsell\DSC\Installs\setup_msipc_x64.msi"
            Sync              = "C:\Powerhsell\DSC\Installs\Synchronization.msi"
            WCFDataServices   = "C:\Powerhsell\DSC\Installs\WcfDataServices.exe" 
            WCFDataServices56 = "C:\Powerhsell\DSC\Installs\WcfDataServices56.exe"
            SQLNCli           = "C:\Powerhsell\DSC\Installs\sqlncli.msi"
            KB2671763         = "C:\Powerhsell\DSC\Installs\AppFabric1.1-RTM-KB2671763-x64-ENU.exe"
            DependsOn         = "[File]SPBinaryDownload"                       
               
        }

**Comment by BrianFarnhill** [comment] 2016-09-11 21:35
Hi there,

This is a duplicate of #244 and has already been fixed. You should upgrade from using the "xSharePoint" module to using "SharePointDsc" as this contains the latest fixes and logic, and will be the module we update going forward.

Thanks for reporting an issue! I'll close this off as a duplicate.

 \- B

**Closed by BrianFarnhill** 2016-09-11 21:35 UTC
