### ISSUE TITLE
SPSite: Primary, Secondary & additional Site Collection Administrators problem

### ISSUE THREAD

**Issue by IlleNilsson** [PowerShell/SharePointDsc#932] opened 2018-10-22 13:42 UTC
#### Details of the scenario you tried and the problem that is occurring
When DSC sets up an SPSite with a Primary and Secondary Site Collection administrator all works well.

But if one add additional Site Collection administrators via:

Get-SPSite | % { Get-SPWeb -Identity $_.Url } | % { **(New-SPUser -Web $_.Url "<DOMAIN\USER>" -SiteCollectionAdmin:$True).Update()** }

Then in CA it shows the account of Primary $ Secondary administrors for Site Collections but their actual administrator priviliges are lost. These admins can not see Site Collection Administration options in Site Settings once DSC has run after adding Site Collection admins via PS-script above.

If I change Site Collection admins in CA to another user and back to the original users, the original users regains their admin priviliges, until DSC runs again.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
                        SPSite $webApplication.DatabaseName {
                            PsDscRunAsCredential = $SpAdminCredential
                            Name = $webApplication.SiteName
                            ContentDatabase = $webApplication.DatabaseName
                            OwnerAlias = $SetupCredential.UserName
                            SecondaryOwnerAlias = $SpAdminCredential.UserName
                            Language = $webApplication.Language
                            Url = "$($webApplication.Url):$($webApplication.Port)"
                            Template = $webApplication.Template
                            DependsOn = @("[SPWebApplication]$($webApplication.DatabaseName)")
                        }
```

#### The operating system the target node is running
On WinSrv2016 Datacenter with WMF 5.1 

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016 SP1

#### Version and build of PowerShell the target node is running
Powershell 5.1 (10.0.14409.102)

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by IlleNilsson** [comment] 2018-10-23 21:28
How can I help?

**Comment by ykuijs** [comment] 2018-10-29 19:40
Hi @IlleNilsson I am not exactly sure what you are doing and when things break. Can you elaborate a little more please?

**Comment by ykuijs** [comment] 2018-12-11 12:07
@IlleNilsson Can you explain your issue a little more? What are you trying to accomplish? Do you have any steps to reproduce?

**Comment by IlleNilsson** [comment] 2018-12-12 18:18
I’m really doing what i describe, but I’m quite shure the issue is resolved with the latest updates to SharePoint itself.

Just don’t close the issue right now.

We are doing a complete rebuild of MinRole farms from Lab, Dev, Test to Prod just now. We will complete before new years.

If I still experience the problem I will leave a comment. If I don’t I will also leave a comment.

BR // Ilian

**Comment by ykuijs** [comment] 2019-01-12 12:02
Hi @IlleNilsson Any update? Has the issue been resolved?

**Comment by IlleNilsson** [comment] 2019-01-12 12:09
Not yet, our sql clusters disks gave up just before new year. I’ll get back to you


________________________________

**Comment by ykuijs** [comment] 2019-01-12 12:10
Ok that is back luck.....good way to start the new years ;-) No worries, I'll wait for an update. Thanks!

**Comment by ykuijs** [comment] 2019-02-12 04:20
(Message to get the Stale label removed)

@IlleNilsson Any update?

**Comment by IlleNilsson** [comment] 2019-03-27 15:03
Problem is real, I have set up four environments. When I change Primary or Secondary owner of a site manually. They get changed back to what SharePointDSC dictates. But permissions are lost for the dictaded user by DCS.

**Comment by IlleNilsson** [comment] 2019-03-27 15:07
Don't get me wrong, the user should be reverted, set by DCS. But the privileges should also follow.

**Comment by ykuijs** [comment] 2019-04-23 13:39
Hi @IlleNilsson, is this the same issue as #1052??

**Comment by IlleNilsson** [comment] 2019-04-23 13:41
Yes, I don’t know why SPContentDatabase.FileStorage got in there

**Comment by ykuijs** [comment] 2019-04-23 13:45
Ok, I'll close this one as duplicate since that contains a little more info about the exact issue you are experiencing.

**Closed by ykuijs** 2019-04-23 13:45 UTC
Labels: duplicate
