### ISSUE TITLE
SPUserProfileSyncService: Get-TargetResource Discussions

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#929] opened 2018-10-19 12:45 UTC
@ykuijs I'd appreciate your feedback on this buddy. 

ReverseDSC is all about making calls to the Get-TargetResource methods with Fake data, in order to retrieve the true values and then call the Set-TargetResource methods properly. Now, I understand that in order to start the UserProfileSyncService, we can't use the Farm Account, and the SET method should prevent users from doing so. However, I would argue that we should not need to throw an error in the Get-TargetResource for this, instead we could use the Test-TargetResource to check if the account passed, is the same that is retrieved by the Get-TargetResource, and that would do a similar job in my opinion. The problem is that ReverseDSC doesn't know what account to use to run the service until it called the GET, and it does so running with the FARM Account.

I would like to propose that we remove the check that prevents the farm account from calling the resource in the Get-TargetResource. Same goes for the SPUserProfileServiceApp.

Thoughts?

**Comment by ykuijs** [comment] 2018-10-23 19:00
The issue is that when not using the Farm account, the code can throw errors because of missing permissions. Where with other resources we write a verbose message and continue execution, with these resources we can run into these permission issues.

An alternative would be to use the Verbose message and always return null values when not using the Farm account. Would that be a solution?

**Comment by ykuijs** [comment] 2018-11-02 12:47
Have been thinking a little more about this issue, but SPUserProfileSyncService requires the specified InstallAccount or PsDscRunAsCredential NOT to be the Farm account. The code retrieves the farm account from the Managed Accounts and impersonates this account in the Set method. The Get method however uses the specified account (Install or RunAs).

Based on this, I am not sure what the issue is you are raising here. Can you elaborate a little more?

**Comment by ykuijs** [comment] 2018-11-12 19:31
@NikCharlebois Can you give a little more info on the issue you are addressing here?

**Comment by ykuijs** [comment] 2018-12-14 21:55
@NikCharlebois Any update?

**Comment by ykuijs** [comment] 2019-01-09 16:34
@NikCharlebois Any updates?

**Comment by ykuijs** [comment] 2019-02-12 04:36
@NikCharlebois Any updates?

**Comment by NikCharlebois** [comment] 2019-02-12 04:38
No, I need to take the time to test this with SP19. Mark it as closed for the moment. Will re-open if still an issue. Thanks mate

**Comment by ykuijs** [comment] 2019-02-12 04:39
Closing issue for now

**Closed by ykuijs** 2019-02-12 04:39 UTC
Labels: discussion
