### ISSUE TITLE
SPUserProfileProperty issue in Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#613] opened 2017-06-06 19:29 UTC
**Details of the scenario you try and problem that is occurring:**
Calling the Get-TargetResource function of the SPUserProfileProperty Resource throws an error the moment you declare a Sync Connection. The following (streamlined) code logic in the Get-TargetResource is causing the issue, because the PropertyMapping value is null for newly created connections. The code should be modified to include a check to ensure the PropertyMapping for the connection is not null first.

    $caURL = (Get-SPWebApplication -IncludeCentralAdministration | Where-Object -FilterScript { 
        $_.IsAdministrationWebApplication -eq $true 
    }).Url
    $context = Get-SPServiceContext -Site $caURL 
    $userProfileConfigManager  = New-Object -TypeName "Microsoft.Office.Server.UserProfiles.UserProfileConfigManager" `
        -ArgumentList $context
    $syncConnection  = $userProfileConfigManager.ConnectionManager | `
        Where-Object -FilterScript { 
            $null -ne $_.PropertyMapping.Item("<whatever>")
    }
      

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 / WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by ykuijs** [comment] 2017-06-07 14:23
Added to backlog

**Comment by ykuijs** [comment] 2017-06-16 11:46
@NikCharlebois, not sure what the issue is. Can you elaborate on it a little more?

**Comment by BrianFarnhill** [comment] 2017-06-19 21:51
@ykuijs In the loop at the end of that sample we see this:

    $_.PropertyMapping.Item("<whatever>")

Here $_.PropertyMappy has the potential to be null, so we should change that line to this:

    $null -ne  $_.PropertyMapping -and $null -ne  $_.PropertyMapping.Item("<whatever>")

that way we make sure it has a value at all before looking to the Item property. Does that make more sense?

**Comment by ykuijs** [comment] 2017-06-29 07:06
Will be fixed in my next Rollup PR

**Comment by BrianFarnhill** [comment] 2017-07-02 22:36
This has been rolled in to dev and will be included in our next release. Closing this issue.

**Closed by BrianFarnhill** 2017-07-02 22:36 UTC
Labels: bug, in progress
