### ISSUE TITLE
SPSite: Issue with encoding when using custom ADFS claims provider 

### ISSUE THREAD

**Issue by Jocorteslopez** [PowerShell/SharePointDsc#1110] opened 2019-09-09 23:28 UTC
**Details of the scenario you tried and the problem that is occurring**
Trying to create a site collection in which the Owner Alias is under a custom ADFS claims provider, the resulting MOF file changes the encoding and the characters that SharePoint understands. Making imposible to create a site collection under this scenario.

**Verbose logs showing the problem**
VERBOSE: [Machinename]:                            [[SPSite]SiteName] Starting New-SPSite with the following parameters: Name=My Test Site; OwnerAlias=**i:0Çµ.t**|ADFS DEV|accountname; Template=STS#0; Url=https://testsite.com/sites/MyTestSite; Verbose=True
....
Exception of type 'System.ArgumentException' was thrown.
Parameter name: encodedValue
    + CategoryInfo          : InvalidData: (Microsoft.Share...SPCmdletNewSite:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSite
    + PSComputerName        : localhost
Exception of type 'System.ArgumentException' was thrown.
Parameter name: encodedValue
    + CategoryInfo          : InvalidData: (Microsoft.Share...SPCmdletNewSite:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSite
    + PSComputerName        : localhost

**Suggested solution to the issue**
Ensure the encoding is UTF-8 .
Follow the explanation link to claims encoding in SharePoint here: https://social.technet.microsoft.com/wiki/contents/articles/13921.sharepoint-20102013-claims-encoding.aspx 

**The DSC configuration that is used to reproduce the issue (as detailed as possible)**
```
SPSite SiteName{
            Url                  = "Url=https://testsite.com/sites/MyTestSite"
            OwnerAlias           = "i:0ǵ.t|ADFS DEV|accountname"
            Name                 = "My Test Site"
            Template             = "STS#0"
            PsDscRunAsCredential = $SetupAccount
            DependsOn            = "[SPWebApplication]Webapp";
        }

```
**The operating system the target node is running**
OsName : Microsoft Windows Server 2016 Standard

Version of SharePoint that is used
SharePoint 2016

**Version and build of PowerShell the target node is running**
5.1.17763.592

**Version of the DSC module that was used**
3.6.0.0

**Comment by Jocorteslopez** [comment] 2019-09-10 15:09
Hello Yorick,

It is not something I can customize, the claim is coming from SharePoint. Please review the section of Custom ADFS Claims here: https://social.technet.microsoft.com/wiki/contents/articles/13921.sharepoint-20102013-claims-encoding.aspx

I know it is a pain...

**Comment by ykuijs** [comment] 2019-09-10 15:11
But in the example config you specified:
```
OwnerAlias           = "i:0ǵ.t|ADFS DEV|accountname"
```
In there, the g has an accent above it. That is something you can change ;-)

**Comment by Jocorteslopez** [comment] 2019-09-10 17:08
Hello Yorick,

I think I'm not explaining myself correctly. Yes the value I'm typing it is a g with an accent but I cannot use only the g because SharePoint is not going to understand the claim. What I'm trying to say, is when you configure SharePoint to use a custom ADFS claims identifier, the token SharePoint uses to identify is the g with the accent, so there is no point from my side to change it because my goal is to setup the site collection owners under adfs identifiers, and with the current logic it is not possible to build it. 

I'm happy to organize a session to show you in live to help to clarify what the issue is if that helps.

**Comment by ykuijs** [comment] 2019-09-10 19:05
Aaaah, now I understand what you mean....sorry for that :-)

The only challenge is to find out how to resolve this. Can you please check if your configuration file is in UTF8? And if the generated MOF file is in UTF8 and has the correct character (just search for SPSite in the MOF file)?

And can you share the ULS log?

**Comment by Jocorteslopez** [comment] 2019-09-10 19:32
The ps1 file we are generating is in UTF-8 but also we tried to use ANSI encryption. Result is the same, when the generated MOF file the encryption is: UCS-2 LE BOM from what I can see.

The ULS is showing this account: i:0Çµ.t|ADFS DEV|accountname that is what is written into the MOF file. 

Basically the ǵ character is translated into Çµ for the encryption. 

I think somehow the MOF file should be written in UTF-8 so it is consistent and the character set remains as it is from the ps1 (specially for this hardcoded values).

I understand the amount of testing that this would require, but definitely it is very annoying scenario.

Thank you for your inputs!

**Comment by ykuijs** [comment] 2019-09-10 19:36
So it looks like the issue is Generic DSC (conversion from ps1 to MOF), not SharePointDsc specific. Do you agree?

I will try to create a simple reproduction and then check with the PowerShell Product Group on how we can resolve this issue.

**Comment by Jocorteslopez** [comment] 2019-09-10 19:39
Yes it could be. Great, thank you for your help!

**Comment by ykuijs** [comment] 2019-09-10 20:13
I just create a test config on my Windows 10 (build 1903) with just the SPSite resource in it, which has your exact config. When I compile the MOF file, it compiles just fine. The file is showing the ǵ character as expected.

```
instance of MSFT_SPSite as $MSFT_SPSite1ref
{
ResourceID = "[SPSite]SiteName";
 Url = "Url=https://testsite.com/sites/MyTestSite";
 PsDscRunAsCredential = $MSFT_Credential1ref;
 OwnerAlias = "i:0ǵ.t|ADFS DEV|accountname";
 SourceInfo = "::7::9::SPSite";
 Name = "My Test Site";
 ModuleName = "SharePointDSC";
 ModuleVersion = "3.5.0.0";
 Template = "STS#0";

 ConfigurationName = "Test";

};
```

Not sure what is different on your end. Maybe the OS has something to do with it. Which patch level are you on?

Will test later on Windows 2016.

**Comment by Jocorteslopez** [comment] 2019-09-10 20:21
oh interesting, can you email me the ps1 file you are using? I would like to try on my end. 
I'll give you the info soon, sorry I can't at this time

**Comment by ykuijs** [comment] 2019-09-10 20:30
Done! Please check your email.

**Comment by ykuijs** [comment] 2019-09-11 10:46
Just tested on Windows Server 2016. There the MOF file also contains the correct character. Really interested in the results of your test of the test config:

```PowerShell
Configuration Test
{
    Import-DscResource -ModuleName SharePointDsc
    node localhost
    {
        SPSite SiteName
        {
            Url                  = "Url=https://testsite.com/sites/MyTestSite"
            OwnerAlias           = "i:0ǵ.t|ADFS DEV|accountname"
            Name                 = "My Test Site"
            Template             = "STS#0"
            PsDscRunAsCredential = $SetupAccount
        }
    }
}
$cd = @{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            PSDscAllowPlainTextPassword = $true
        }
    )
}
Test -ConfigurationData $cd
```

**Comment by Jocorteslopez** [comment] 2019-09-11 14:56
Thank you Yorick,

Checked out form my side and it turned out to be an issue not with DSC but with VSCode Editor. For some reason we are still investigating even though the encoding is setup to UTF-8 in the editor, the character is not saved correctly and powershell doesn’t understand it in the internal treatment.

I replied to your mail with a couple of videos demoing that.

Regards

Jose Manuel Cortes Lopez
Sr Manager Application Development | Tax & Legal, ERS Delivery | Global DAS
Deloitte Touche Tohmatsu
Tel/Direct: +1 312 486 0740  Mobile: +1 312 339 1061
www.deloitte.com

**Comment by ykuijs** [comment] 2019-09-11 18:43
You are right. Just created a new file in VSCode and pasted the test config in there. When I run it, the MOF file now contains the other characters. When opening the script file in Notepad, the correct character is displayed, but when opening the file in PS ISE the incorrect characters reappear.

I think this is an issue in VSCode, so I suggest to create a bug in the [VS Code repo](https://github.com/Microsoft/VScode)

**Comment by ykuijs** [comment] 2019-09-19 10:41
Since this is a VSCode issue, I suggest we close this issue. Do you agree @Jocorteslopez?

**Comment by Jocorteslopez** [comment] 2019-09-19 14:42
Hello Yorick,

Yes absolutely this can be close.

Thanks so much

Jose Manuel Cortes Lopez
Sr Manager Application Development | Tax & Legal, ERS Delivery | Global DAS
Deloitte Touche Tohmatsu
Tel/Direct: +1 312 486 0740  Mobile: +1 312 339 1061
www.deloitte.com

**Closed** 2019-09-24 09:19 UTC
Labels: bug, help wanted, needs investigation
