### ISSUE TITLE
SPDistributedCacheService provisions nothing

### ISSUE THREAD

**Issue by dmercc** [PowerShell/SharePointDsc#681] opened 2017-11-14 14:50 UTC
**Details of the scenario you try and problem that is occurring:**

The problem I have is that the Farm account gets to be the serviceaccount for the distributed cache service and I want to change that but the "SPDistributedCacheService" resource doesn't provision that,
It doesn't set the specified serviceaccount.

If I say "Ensure = "Absent"" it gets removed. If I change it back to Present it doesn't provision. When I run verbose it says it skips set. If I then try to change back to "Absent" it says that there is no distributed cache service instance to be removed. Changing it back to "Present" again, it skips set...

**The DSC configuration that is using the resource:**

        SPDistributedCacheService EnableDistributedCache
        {
                Name                 = "AppFabricCachingService"
                Ensure               = "Present"
                CacheSizeInMB        = 4096
                ServiceAccount       = $SVCAPP.UserName
                InstallAccount       = $SPAdmin
                CreateFirewallRules  = $false
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**

Windows Server 2016
Powershell 5.1.14393.1715

**Version of the DSC module you're using:**

1.8.0.0

**Comment by ykuijs** [comment] 2017-11-15 15:21
Linking to issue #547, which is related but closed due to inactivity

**Comment by ykuijs** [comment] 2017-12-14 20:30
Found the cause, implemented a fix. Will be included in the v2.0 release

**Comment by ykuijs** [comment] 2017-12-15 07:37
Merged in PR 697

**Closed by ykuijs** 2017-12-15 07:37 UTC
Labels: Investigating
