### ISSUE TITLE
XSPCreatefarm fails when using configurationnames and 'localhost'

### ISSUE THREAD

**Issue by Bjorn80** [PowerShell/SharePointDsc#393] opened 2016-08-23 12:27 UTC
**Details of the scenario you try and problem that is occurring:**
Using MS Server 2012R2 with WMF 5. SharePoint Server 2013 SP1 and SQL 2014 Server.
Confguration set up with ConfigurationNames. When specifying 'localhost' instead of nodenames (hostname), the XSPCreateFarm resource fails with:
`VERBOSE: [vm09]:                            [[xSPCreateFarm]CreateSPFarm] Creating a new farm with config db SP_Config content db SP_AdminContent server localhost\sql2014 for farm mode
localhost is an invalid or loopback address.  Specify a valid server address.
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSPConfigurationDatabase
    + PSComputerName        : localhost

VERBOSE: [vm09]:                            [[xSPCreateFarm]CreateSPFarm] Leaving ProcessRecord Method of New-SPConfigurationDatabase.
VERBOSE: [vm09]:                            [[xSPCreateFarm]CreateSPFarm] Leaving EndProcessing Method of New-SPConfigurationDatabase.
VERBOSE: [vm09]:                            [[xSPCreateFarm]CreateSPFarm] Leaving BeginProcessing Method of Install-SPHelpCollection.
VERBOSE: [vm09]: LCM:  [ End    Set      ]  [[xSPCreateFarm]CreateSPFarm]  in 5.4220 seconds.
PowerShell DSC resource MSFT_xSPCreateFarm  failed to execute Set-TargetResource functionality with error message: Cannot access the local farm. Verify that the local farm is properly configured, currently available, and that you have
the appropriate permissions to access the database before trying again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost `

**The DSC configuration that is using the resource:**
XSPCreateFarm
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Server 2012R2 WMF 5
**Version of the DSC module you're using:**
0.12.0.0

If i input the correct nodename instead of 'localhost', the code completes successfully.
But aim to use configurationname is to avoid adding spesific nodenames into the configuration. So I would like to use the 'localhost'.

brgs

Bjørn Roalkvam

**Comment by Bjorn80** [comment] 2016-08-23 13:02
Seem to get the same issue with the service applications, search and MMSA. The two I am adding to the farm. A change to the node hostname fixes it.

Brgs

Bjørn

**Comment by MikeLacher448** [comment] 2016-08-24 00:30
I imagine this is really only useful in a single server topology? As soon as you branch to a multi server farm, you will reference node names again. Node names do not need to be in the configuration file, they can be piped in via configuration data. I'm just trying to understand the use case?

**Comment by BrianFarnhill** [comment] 2016-08-24 00:33
Changing the nodename though should only impact what gets output to the MOF file - once you have a MOF the instructions that are handed to the LCM are exactly the same.

Are you open to open the .MOF file for localhost.mof and hostname.mof when you use either of those and find the SPCreateFarm resource in there and share that with us so we can compare the two of those?

@MikeLacher448 Yes and no for the single server stuff. If you are using the DSC extension for Azure virtual machines it always uses localhost as the config there because of how they do credential encryption on individual nodes using a machine certificate, so there are scenarios where localhost would still be used for multi-server configs.

**Comment by Bjorn80** [comment] 2016-08-24 12:43
Hi Mike and Brian, thank you for the replies.

My xSPcreateFarm are as follows:

`instance of MSFT_xSPCreateFarm as $MSFT_xSPCreateFarm1ref
{
ResourceID = "[xSPCreateFarm]CreateSPFarm";
FarmAccount = $MSFT_Credential25ref;
PsDscRunAsCredential = $MSFT_Credential26ref;
Passphrase = "Ioasdjfuashf87ewh";
SourceInfo = "::455::9::xSPCreateFarm";
FarmConfigDatabaseName = "SP_Config";
ModuleName = "xSharePoint";
AdminContentDatabaseName = "SP_AdminContent";
ModuleVersion = "0.12.0.0";
DatabaseServer = "sqlserver\\sql2014";

DependsOn = {

    "[xSPInstall]InstallSharePoint"};

ConfigurationName = "SQLSharePointInstall";

};





instance of MSFT_xSPCreateFarm as $MSFT_xSPCreateFarm1ref
{
ResourceID = "[xSPCreateFarm]CreateSPFarm";
FarmAccount = $MSFT_Credential25ref;
PsDscRunAsCredential = $MSFT_Credential26ref;
Passphrase = "Ioasdjfuashf87ewh";
SourceInfo = "\\\\vm01\\\\Script\\SqlSharePointMerged\\SQL_SharePoint_Config_Complete_Localhost3.ps1::455::9::xSPCreateFarm";
FarmConfigDatabaseName = "SP_Config";
ModuleName = "xSharePoint";
AdminContentDatabaseName = "SP_AdminContent";
ModuleVersion = "0.12.0.0";
DatabaseServer = "localhost\\sql2014";

DependsOn = {

    "[xSPInstall]InstallSharePoint"};

ConfigurationName = "SQLSharePointInstall";

}; 

`



If i pipe multiple nodes into the configuration data, It will create one Mof file per node right?
A typical SharePoint farm here will be: 1 SQL Server, 2 Web Servers and 2 backend Servers.

Would it be better to divide nodes in roles in the configuration data, creating multiple node mofs? How would I then configure the nodes LCM to pull its correct configuration? Must I  use configuration-ids instead of configuration-names?

brgs

Bjørn

**Comment by BrianFarnhill** [comment] 2016-08-24 22:14
Ahhhhh, ok so I missed the message in your original logs:

    localhost is an invalid or loopback address. Specify a valid server address.

This isn't actually a DSC error, it's a SharePoint issue - basically you need to use valid DNS names for SQL server when you use SharePoint, you can't actually use "localhost" for the database server. Firstly this would only ever work for a single server deployment, so your multiple server setup wouldn't like this as "localhost" would be different for all the SharePoint boxes. But the main issue is that to prevent that sort of thing there is a check internally around this that is documented by our SQL support team at [https://blogs.msdn.microsoft.com/psssql/2013/10/04/invalid-or-loopback-address-when-configuring-sharepoint-against-a-sql-server/](https://blogs.msdn.microsoft.com/psssql/2013/10/04/invalid-or-loopback-address-when-configuring-sharepoint-against-a-sql-server/).

So I'm assuming you are also using the node name in the "DatabaseServer" property of SPFarm there, which is the only difference between the MOF file outputs, and when the node is localhost this causes it to create an invalid property for SharePoint.

Based on that, we can call this one "by design" and close it off. 

To answer your other questions though, yes one config per "role" is generally how we do things, but have a look at [my presentation from Ignite NZ last year](https://channel9.msdn.com/events/Ignite/Microsoft-Ignite-New-Zealand-2015/M388) where I talk about multi-server configurations, it might help answer your questions. 

Thanks Bjørn!

**Closed by BrianFarnhill** 2016-08-24 22:14 UTC
Labels: Investigating

**Comment by Bjorn80** [comment] 2016-08-25 07:21
Thank you for clearing that up Brian.
brgs

Bjørn
