### ISSUE TITLE
ability to change SuiteBarBrandingElementHtml

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/SharePointDsc#655] opened 2017-09-13 13:45 UTC
**Details of the scenario you try and problem that is occurring:**
My customer wants to be able to change the "SharePoint" branding text at the web application level. This is a set by the SuiteBarBrandingElementHtml property of the web application. 

I want to add this to SharePointDSC, but just want to get a consensus if this should be an additional, optional property of SPWebAppGeneralSettings, or if a new resource should be started for it?

**The DSC configuration that is using the resource:**
none yet

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012R2 / Windows Server 2016

**Version of the DSC module you're using:**
1.9

**Comment by BrianFarnhill** [comment] 2017-09-14 00:59
OK so this is just a property off the SPWebApplication object, so it's easy enough for us to implement in either the SPWebApplication resource or the SPWebAppGeneralSettings resources (I don't think I'm massively fussed on which, I think I would rather the SPWebApplication one though since the "general settings" one was designed to mimic the settings layout of the central admin UI and this property isn't surfaced through a UI anywhere).

A part of me also looks at this as with my "I don't wanna do UI customisation in DSC" glasses and wants to back away from it though - but then it's literally just a property on the web app, which makes me totally fine with it it too, so I've got some mixed emotions on it. But I think if we make it a property to go on the SPWebApplication resource that it should be fine.

@ykuijs You got any thoughts on this one dude?

**Comment by ykuijs** [comment] 2017-09-14 08:48
I did some checking of this property (never used it before :-)) and it looks like it is SP2013 only. In SP2016 there are some more properties/possibilities:
https://sharepoint.stackexchange.com/questions/177733/sp2016-change-suite-bar

In SP2013 you have to specify HTML code and in SP2016 there are multiple text only properties. So if we are going to implement this, we need to take this into account which makes it more complex. Both to implement and in use (multiple properties, one 2013 only and multiple 2016 only properties).

So I am a bit in doubt. If we can come up with a nice way to implement which is user friendly, I am all for it.

**Comment by BrianFarnhill** [comment] 2017-09-15 01:50
Good catch @ykuijs that does make things more interesting.

We could put in a resource that has all the individual properties from both versions, and then throw errors if you use one that doesn't suit the version you have installed? It's not super graceful but it would do the trick.

We could also just use the text properties from SP2016 and assume the HTML needed to replicate that in 2013 so that we build the HTML based on the properties and update it accordingly on the fly if that makes sense? That's a little more use friendly but more leg work on our end to make it work - but doable I think.

**Comment by NikCharlebois** [comment] 2017-09-15 12:28
My vote goes out to having the resource accept all possible properties, and have internal logic throw an error if the property does not belong to that SP version. Otherwise we would be making an assumption on behalf of the user, which is not the way to go.

**Comment by MikeLacher448** [comment] 2017-09-15 19:47
so it sounds like a dedicated resource that works on both 2013/2016 is the way to go? Or roll the properties in with SPWebApplicaiton ?

**Comment by BrianFarnhill** [comment] 2017-09-17 23:00
If we are gonna have to put version specific logic in it, my vote goes to an independent resource. And I agree with Nick there on how to implement it as well.

**Comment by NikCharlebois** [comment] 2017-10-06 11:49
@ykuijs assign that one to me.

**Comment by ykuijs** [comment] 2017-10-06 15:50
Somehow Github doesn't allow me to assign you, but it is all yours!

**Comment by NikCharlebois** [comment] 2017-10-18 16:44
@MikeLacher448 Fixed in PR #662

**Comment by ykuijs** [comment] 2017-11-08 10:57
Merged in PR662

**Closed by ykuijs** 2017-11-08 10:57 UTC
Labels: enhancement, in progress
