### ISSUE TITLE
MSFT_SPInstallPrereqs: MSVCRT11 missing

### ISSUE THREAD

**Issue by BBokdam** [PowerShell/SharePointDsc#986] opened 2018-11-27 10:00 UTC
#### Verbose logs showing the problem
When installing SharePoint 2019 the prereq MSVCRT11 is not required
#### Suggested solution to the issue
Add the MSVCRT11 to the requirements of SharePoint 2019
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
`PInstallPrereqs InstallPrereqs {
            IsSingleInstance  = "Yes"
            Ensure            = "Present"
            InstallerPath     = "media\Sharepoint2019\PrerequisiteInstaller.exe"
            OnlineMode        = $false
            SXSpath           = "\media\SXS"
            KB3092423         = "\media\PreRequirements\sp2019\AppFabric-KB3092423-x64-ENU.exe"
            IDFX11            = "media\PreRequirements\sp2019\MicrosoftIdentityExtensions-64.msi"
            MSIPCClient       = "\\media\PreRequirements\sp2019\setup_msipc_x64.exe"
            SQLNCli           = "\media\PreRequirements\sp2019\sqlncli.msi"
            WCFDataServices56 = "media\PreRequirements\sp2019\WcfDataServices.exe"
            AppFabric         = "media\PreRequirements\sp2019\WindowsServerAppFabricSetup_x64.exe"
            DotNet472     = "\media\PreRequirements\sp2019\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
            Sync              = "\media\PreRequirements\sp2019\Synchronization.msi"
            MSVCRT11          = "\media\PreRequirements\sp2019\vcredist_x64.exe"
            MSVCRT141          = "\media\PreRequirements\sp2019\vc_redist.x64.exe"
        }
#### The operating system the target node is running

OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2608.amd64fre.rs1_release.181024-1742
OsLanguage           : en-US
OsMuiLanguages       : {en-US} 

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019
#### Version and build of PowerShell the target node is running

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
PSVersion                      5.1.14393.2608                                                                                                                         
PSEdition                      Desktop                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                
BuildVersion                   10.0.14393.2608                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                        
WSManStackVersion              3.0                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                    
SerializationVersion           1.1.0.1     

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.0

**Comment by ykuijs** [comment] 2018-11-27 10:02
Have potentially identified the cause of this issue and am working with @BBokdam on testing a solution. Will include the fix in my next Bugfix PR.

**Comment by ykuijs** [comment] 2018-11-27 12:52
Solution works. Will be included in my next Bugfix PR

**Closed** 2018-11-27 15:53 UTC
Labels: bug, in progress
