### ISSUE TITLE
Question: Configure share point on multiple VMs

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#710] opened 2017-12-25 01:10 UTC
Hello,
I have a scenario to deploy share point in on prem environment . My environment contains multiple role (E.g. APs, FEs,SQLs etc)VMS . I have a config which deploys share point on a single VM(Thanks to Nik) , however I would like to add other roles to the share point farm deployed in the first VM. I would like to understand how the config look like .e.g.   here I am putting my thougt process and wondering if you have any samples that I can refer

Configuration sharepoint
{ 
    param 
    ( 
        
    ) 
    /* config content */
   # if role contains sql -execute sqlconfig
   # if role contains ap -deploybuild and configure farm
   #If role contains fe - deploythe build Join to the configured farm in AP
 }

$ConfigData = @{ 
                 AllNodes = @(  
                              @{     
                                 NodeName = "*"  
}
                          @{     
                                 NodeName = "SQL VM"
                                 Role = "SqlServer"                       
                                 }  
@{     
                                 NodeName = "Frontendvm"
                                 Role = "fe"                       
                                 }  

)
}

Appreciate your inputs.

**Comment by NikCharlebois** [comment] 2018-01-02 13:57
Hi @rsganta the "Node" keyword is what determines how many servers will be configured by your Config. In your configuration script, simply make sure that you define a Node entry for each server in your farm (in your case with the Configuration Data .psd1). This will results in multiple .MOF files (one per server) to be created. Upon running Start-DSCConfiguration, PowerShell will remotely configure all servers represented by a MOF file in your config location.

**Comment by ykuijs** [comment] 2018-01-04 20:09
Hi @rsganta, does the answer fix your issue? If so, can you please close the issue or let us know so we can do it for you ;-)

**Comment by ykuijs** [comment] 2018-01-11 12:03
Assuming the issue is fixed, since no reply on the last comment has been added. Please reopen the issue if the issue still exists

**Closed by ykuijs** 2018-01-11 12:03 UTC
Labels: question
