### ISSUE TITLE
SPFarm: Start-DscConfiguration simultaneously on several servers fails

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#765] opened 2018-02-07 19:46 UTC
**Details of the scenario you try and problem that is occurring:**
I'm currently using SharePoint DSC in a multi server environment (SP05, SP06). 

I start the DSC configuration with the following command:

`Start-DscConfiguration -Verbose -Wait -Path <dir with mof files>`

The directory with the mof files contains one for SP05 and one for SP06.
The configurations steps prior to SPFarm are very similar and already in their desired state. 

During the configuration apply, there are several error messages:

```
VERBOSE: [sp05]: LCM:  [ Start  Set      ]  [[SPFarm]CreateOrJoinSharePointFarm]
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Setting local SP Farm settings
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Getting the settings of the current local SharePoint 
Farm (if any)
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Detected installation of SharePoint 2016
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Executing as the local run as user DEV\_SP365_t
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Loading module from path 'C:\Program Files\WindowsPow
erShell\Modules\SharePointDSC\2.0.0.0\Modules\SharePointDsc.Farm\SPFarm.psm1'.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Exporting function 'Get-SPDSCConfigDBStatus'.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Exporting function 'Add-SPDSCConfigDBLock'.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Exporting function 'Remove-SPDSCConfigDBLock'.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Importing function 'Add-SPDSCConfigDBLock'.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Importing function 'Get-SPDSCConfigDBStatus'.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Importing function 'Remove-SPDSCConfigDBLock'.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Detected Version: SharePoint 2016 - configuring serve
r as ApplicationWithSearch
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] The SharePoint config database 'SP_Admin_Config' does
 not exist, so this server will create the farm.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Leaving BeginProcessing Method of New-SPConfiguration
Database.
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Entering function SPCmdletNewSPConfigurationDatabase.
InternalProcessRecord
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Creating connection string for config db SP_Admin_Con
fig server SQLSERVER
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Creating connection string for admin content db SP_Ad
min_Content server SQLSERVER
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Using NTLM for sql connection string
VERBOSE: [sp05]:                            [[SPFarm]CreateOrJoinSharePointFarm] Creating a new farm with config db SP_Admin_Config co
ntent db SP_Admin_Content server SQLSERVER for farm mode
There is a compatibility range mismatch between the Web server and database "", and connections to the data have been blocked to due 
to this incompatibility. This can happen when a content database has not been upgraded to be within the compatibility range of the 
Web server, or if the database has been upgraded to a higher level than the web server. The Web server and the database must be 
upgraded to the same version and build level to return to compatibility range.
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase
    + PSComputerName        : sp06
 
VERBOSE: [sp06]:                            [[SPFarm]CreateOrJoinSharePointFarm] Leaving ProcessRecord Method of Connect-SPConfigurati
onDatabase.
VERBOSE: [sp06]:                            [[SPFarm]CreateOrJoinSharePointFarm] Leaving EndProcessing Method of Connect-SPConfigurati
onDatabase.
VERBOSE: [sp06]:                            [[SPFarm]CreateOrJoinSharePointFarm] Leaving BeginProcessing Method of Install-SPHelpColle
ction.
VERBOSE: [sp06]: LCM:  [ End    Set      ]  [[SPFarm]CreateOrJoinSharePointFarm]  in 17.9930 seconds.
PowerShell DSC resource MSFT_SPFarm  failed to execute Set-TargetResource functionality with error message: Cannot access the local 
farm. Verify that the local farm is properly configured, currently available, and that you have the appropriate permissions to 
access the database before trying again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : sp06
 
VERBOSE: [sp06]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : sp06
 
VERBOSE: Operation 'Invoke CimMethod' complete.
```

The node SP06 did stop its configuration, SP05 is still working on it. 

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2016
**Version of SharePoint that is used (e.g. SharePoint 2016):**
2016
**Version of the DSC module you're using:**
2.0.0.0

**Comment by MikeLacher448** [comment] 2018-02-16 23:16
have you verified that any databases were created on the SQL server?

**Comment by andikrueger** [comment] 2018-02-17 11:29
Yes, I did. Running the configuration a second time helped. The farm got created finde afterwards. I will try to reproduce this issue again.

**Comment by andikrueger** [comment] 2018-03-12 09:49
I ran several tests by now and was not able to reproduce this issue. I will close this issue. If the problem occurs again, I will reopen it.

**Comment by ronx** [comment] 2018-03-30 18:09
FWIW, I've hit this same issue twice in a row in my Azure lab while testing the PLA build. Stopping the config and force starting again gives a verbose message saying that another process is still provisioning the config database and then it continues fine. Workaround seems easy enough, but we should probably keep this on the radar for further investigation.

**Comment by ronx** [comment] 2018-03-30 18:11
BTW, since I reopened, I'm happy to take some accountability for helping reproduce and test it.

**Comment by andikrueger** [comment] 2018-03-30 18:48
I saw this issue in an Azure Lab too. Maybe this is correlated. Never happend to me before in any on-premises environment.

Are you still having the verbose logs for the failing configuration? I think the join farm operation might happen the same time the configuration DB creation process is still ongoing. This would match the error message I saw:
```
There is a compatibility range mismatch between the Web server and database "", and connections to the data have been blocked to due 
to this incompatibility. This can happen when a content database has not been upgraded to be within the compatibility range of the 
Web server, or if the database has been upgraded to a higher level than the web server. The Web server and the database must be 
upgraded to the same version and build level to return to compatibility range.
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase
    + PSComputerName        : sp06
```

**Comment by ronx** [comment] 2018-03-30 21:17
I don't have the log output unfortunately, but I'm sure I can recreate it if needed after this round of testing. It was the same as what you pasted above though. And yes, I agree with you about it being a timing issue. Looking at the code, all non-CA servers will keep trying to join the farm every 60 seconds for 15 minutes. It does this by calling Connect-SPConfigurationDatabase. I'm guessing that there's a window of time where the config database has been created but hasn't finished, during which time Connect-SPConfigurationDatabase experiences a non-terminating error that isn't handled by the try-catch. I wonder if adding "-ErrorAction Stop" to the end of Connect-SPConfigurationDatabase would fix this by making sure that any error is treated as terminating and allowing the catch to handle the expected behavior.

**Comment by andikrueger** [comment] 2018-03-31 11:42
That's a good idea! We could also add the parameter "ErrorVariable". When we are seeing the error message above, we can change the behaviour of the resource, so that we wait for the farm creation.

I have doubts, when we only use error action to get terminating errors. I don't know what other non-terminating errors are produced by this cmdlet.

**Comment by ykuijs** [comment] 2018-06-20 08:10
@andikrueger, @ronx: Do you guys have any update on this issue?

**Comment by andikrueger** [comment] 2018-06-20 12:27
Currently not. I haven't stumbled across the problem lately.

**Comment by ykuijs** [comment] 2018-06-21 18:14
Ok, please reopen the issue reoccurs. Closing for now.

**Closed by ykuijs** 2018-06-21 18:14 UTC
Labels: bug, needs more information
