### ISSUE TITLE
SPShellAdmins, when using Setup account, 5 databases fail.

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/SharePointDsc#797] opened 2018-05-07 14:08 UTC
**Details of the scenario you try and problem that is occurring:**
When using the 'AllDatabases' parameter, SPShellAdmins resource will fail to run on the following databases.
 Secure Store
 BCS
 UPA Social DB
 UPA Profile DB
 UPA Sync DB

This is because these databases set the farm account as the db owner, and not the setup account. 

A couple COAs to solve this:

- add support for specifying 'All Content Databases', and use multiple instances of the resource to handle content and service app databases separately.
- add support for specifying an 'exclude list', excluding the databases that use the farm account as db owner, and specifying separate instances of the resource to handle those separately.

 

**The DSC configuration that is using the resource:**
SPShellAdmins ShellAdmins
                {
                    Name                = "Farm Shell Admins"
                    Members             = $SPFarmConfig.ShellAdmins
                    AllDatabases = $true
                    PsDscRunAsCredential      = $SetupAccount
                }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016,  PS 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2016

**Version of the DSC module you're using:**
SPDSC 2.2

**Comment by ykuijs** [comment] 2018-05-07 14:13
@MikeLacher448 Can you post the error message you are getting? Wondering if this is an "Access Denied" (the resource does not have the correct permissions to set the Shell Admins) issue or an issue where the Setup account cannot be configured due to the fact that it already has another database role configured in SQL (like owner of a database)

**Comment by MikeLacher448** [comment] 2018-05-07 20:32
I don't have a screen shot, as I manually fixed the permissions and moved on. It was an 'Access Denied', and I fixed it by adding the setup account as a user of the DB, with db_owner and SP_DataAccess roles.

When I get a chance, I'll do a new deployment and get exact error message.

**Comment by ykuijs** [comment] 2018-07-12 07:28
This week I did some testing with this resource for another project. I discovered that updating the ShellAdmins requires very specify permissions. Only when I granted the account that was making the change (the setup account in your case) db_owner permissions, I was able to update the permissions properly.

This is however an issue with SharePoint, not with SharePointDsc (was able to reproduce the issue with just PowerShell).

**Comment by ykuijs** [comment] 2018-07-12 07:37
On https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/add-spshelladmin?view=sharepoint-ps, the following is mentioned:
"When you run this cmdlet to add a user to the SharePoint_Shell_Access role, you must have membership in the securityadmin fixed server role on the SQL Server instance, membership in the db_owner fixed database role on all affected databases, and local administrative permission on the local computer."

I think this explains the issues you were having. I will update the documentation of the SPShellAdmins resource.

**Comment by MikeLacher448** [comment] 2018-07-13 15:49
how about adding a 'ExcludeDatabases' parameter, so we can run this as essentially AllDatabases, except these... ?

**Comment by ykuijs** [comment] 2018-08-30 11:06
Great idea, have implemented this. Will be included in my next PR.

**Closed** 2018-08-31 11:52 UTC
Labels: enhancement, in progress
