### ISSUE TITLE
Remove dependency on CredSSP

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#389] opened 2016-08-16 23:00 UTC
**Details of the scenario you try and problem that is occurring:**

Currently both SPUserProfileServiceApp and SPUserProfileSyncService rely on CredSSP being configured to impersonate the farm account. This should be removed, instead using the farm account credential in either the InstallAccount (for PowerShell 4) or PsDscRunAsCredential (for PowerShell 5) parameters and then have the resource check that the credential it was given is actually the farm account. This will ensure that we can run a deployment with CredSSP being disabled entirely (which can improve security) 

**Version of the DSC module you're using:**

SharePointDsc 1.2

**Comment by NikCharlebois** [comment] 2016-10-04 18:34
Brian, this may sound stupid, but why not continue to let the user pass in the $FarmAccount param, but then within the "Set-TargetResource", just before calling the Invoke-SPDSCCommand, check the $PSVersionTable and then swap the params accordingly. If the Major Version is 4, then pass in the farm account param as we currently do, and if it's 5 or greater, then put the $FarmAccount creds in the PsDscRunAsCredential and pass in $null creds as $Credentials to ensure CredSSP is not called.

I guess that I am getting confused where you say "...then have the resource check that the credential it was given is actually the farm account." We somehow have to assume the parameter passed on by the user is indeed the farm account and simply make a decision based on the WMF version.

Thoughts?

**Comment by BrianFarnhill** [comment] 2017-02-02 22:28
Late reply here - we already have logic to test if a credential given is the farm account (I have it somewhere around here) so the plan is to use that and then provide feedback as appropriate.

**Comment by BrianFarnhill** [comment] 2017-02-02 22:28
Further to that, this falls in to the breaking change category as we will be taking properties away so I'll tag it as that.

**Comment by ykuijs** [comment] 2017-05-23 08:44
I am working on implementing breaking changes for v2.0. Since this is one of them, I would like to implement a fix. Unfortunately I am not sure what the issue is and what has to be changed. @BrianFarnhill can you elaborate a little?

Do we really want to run DSC as the Farm account? The Best Practices are to use an Install account for installing/configuring SharePoint and leave the Farm account for SharePoint to use. If the Farm account is required in some cases we do not have another option, but to enforce using the Farm account is a bad practice.

**Comment by BrianFarnhill** [comment] 2017-05-23 12:33
@ykuijs I'm not proposing we run the entire config with the farm account, that can't be done without local admin and that's not gonna fly. I'm saying we need to change it so we expect SPUserProfileServiceApp and SPUserProfileSyncService to run as the farm account, because we already run the logic as these accounts anyways (through the FarmAccount property, look through the code) - all im asking is that we remove the FarmAccount bit and do it so that either InstallAccount or PsDscRunAsCredential has to be the farm account for these resources only. Does that make more sense? Then we test in those resources if they are running as the farm account and give an error if they aren't, but everything else runs as the setup account as well.

**Comment by ykuijs** [comment] 2017-05-23 13:38
@BrianFarnhill That is what I saw after reading through this issue and the code some more, good to see that ;-)

So basically this change means:
1. Remove the Farm account parameter
2. Update the resources to check if the install account or PsDscRunAsCredential is the farm account and if not, throw an exception.
3. Update the documentation to reflect this requirement

In what way does this method remove the dependency on CredSSP? If using InstallAccount we still be using CredSSP, right? In PS5+ and PsDscRunAsCredential, using CredSSP isn't needed anymore.

**Comment by BrianFarnhill** [comment] 2017-05-23 22:01
It removes the dependency on CredSSP by giving you an option to work without it. Yes InstallAccount will still require it, but at that point PsDscRunAsCredential will not - so the option to not use CredSSP will require PowerShell 5, but there will at least be an option there. Given the more security conscious are the ones who don't want to enable CredSSP, they are more likely to be up to date, so I don't see this being an issue in this case. In any event, there is no way we can make InstallAccount work without CredSSP (or going down the kerberos path, which I think isn't practical in terms of how we would manage the code) so this is the best possible solution I believe.

**Comment by ykuijs** [comment] 2017-06-07 14:05
Working on this issue and running into a challenge. Wondering if one of you guys has a solution:
In https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1 on line 222, I have to provide the farm account password. When using the InstallAccount parameter, I can easily retrieve this from the variable. But how to get that when using PSDSCRunAsCredentials??

**Comment by NikCharlebois** [comment] 2017-06-07 14:54
The closest we'll get inside the Resource is the use of $PSDscContext which returns information about the user set as PSDscRunAsCredentials, but there's no way to grab the password from there. The only other option I can think of is for us to create yet another resource, and use @BrianFarnhill solution to store the encrypted credentials in a registry key (which seems like a very bad hack for this scenario)

**Comment by ykuijs** [comment] 2017-06-07 15:16
Just did some digging. What about the following command:
$Farm_pass = C:\Windows\System32\cmd.exe /q /c $env:windir\system32\inetsrv\appcmd.exe list apppool "SecurityTokenServiceApplicationPool" /text:ProcessModel.Password

**Comment by ykuijs** [comment] 2017-06-29 20:42
What about my last suggestion? Do you guys see any issue with it?

**Comment by BrianFarnhill** [comment] 2017-06-29 23:10
What if we just leave FarmAccount as a property here so we can get the password out of it for that method? I feel like that's fair enough as we need it for the password value, and we just avoid using it for any kind of RunAs functionality so we can still ditch CredSSP?

**Comment by ykuijs** [comment] 2017-07-04 21:39
Sounds like a plan. Will do that!

**Comment by ykuijs** [comment] 2017-08-25 14:53
Fixes merged into 2.0 branche

**Closed by ykuijs** 2017-08-25 14:53 UTC
Labels: breaking change, enhancement, in progress, Technical Debt
