### ISSUE TITLE
SPShellAdmins resource throws error stating Get-SPDSCContentDatabase not recognized

### ISSUE THREAD

**Issue by iosgitr** [PowerShell/SharePointDsc#428] opened 2016-10-17 22:21 UTC
**Details of the scenario you try and problem that is occurring:**
Trying to ensure an AD user is an SP shell admin.

**The DSC configuration that is using the resource:**
configuration SharePointConfig
{
	Import-DSCResource -ModuleName PSDesiredStateConfiguration -ModuleVersion "1.1"
	Import-DscResource -ModuleName SharePointDsc -ModuleVersion "1.3.0.0"

	node farmnode1
	{
		SPShellAdmins SharePointShellAdmins
		{
			AllContentDatabases = $true
			MembersToInclude = "[my AD user]"
			Name = "SharePointShellAdmins"
			PsDscRunAsCredential = $CredentialSet.ConfigCredential
		}
	}
}

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2 and WMF 5.0

**Version of the DSC module you're using:**
1.3.0.0

**Comment by iosgitr** [comment] 2016-10-17 22:21
This is the error I get:

PowerShell DSC resource MSFT_SPShellAdmins  failed to execute Test-TargetResource functionality with error message:
The term 'Get-SPDSCContentDatabase' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by iosgitr** [comment] 2016-10-17 22:22
I found that function in the bottom of the MSFT_SPShellAdmins.psm1 file so not sure why the LCM can't find it.

**Comment by BrianFarnhill** [comment] 2016-10-17 22:27
This is a duplicate of #383 and was fixed in #415 - this will be released as part of version 1.4 which should go out towards the end of this month. In the mean time if you need this fix you can grab the latest code from our dev branch which should resolve the issue.

Closing this as a duplicate. Thanks for reporting.

**Comment by iosgitr** [comment] 2016-10-17 22:28
Sorry!  Thanks for the response.  I'm still learning my way around GitHub.

**Closed by BrianFarnhill** 2016-10-17 22:27 UTC
