### ISSUE TITLE
MSFT_SPUserProfileServiceApp wrong error message

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#616] opened 2017-06-09 12:08 UTC
**Details of the scenario you try and problem that is occurring:**
Using the DSC block below, I get the following error thrown. However, I am only using the PsDSCRunAsCredential.

PowerShell DSC resource MSFT_SPUserProfileServiceApp  failed to execute Set-TargetResource 
functionality with error message: Unable to use both InstallAccount and 
PsDscRunAsCredential in a single resource. Remove one and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**The DSC configuration that is using the resource:**
SPUserProfileServiceApp b21cffb0-2ec0-4226-aadd-9fba1090a4b1
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            ApplicationPool = "SharePoint Hosted Services";
            ProxyName = "User Profile Service Application Proxy";
            ProfileDBName = "DW_Profile";
            FarmAccount = $Credsdw_spfarm;
            Name = "User Profile Service Application";
            SocialDBName = "DW_Social";
            Ensure = "Present";
            EnableNetBIOS = $True;
            SyncDBServer = $env:Computername
            ProfileDBServer = "SharePointDB";
            SyncDBName = "DW_Sync";
            SocialDBServer = $env:Computername
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win2k12 R2/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by ykuijs** [comment] 2017-06-09 14:56
I believe this is because you are also using the Farm account as the PsDscRunAsCredential, just like with issue #592. Will be fixed with issue #389 in v2.0.

**Comment by BrianFarnhill** [comment] 2017-06-13 04:11
Agreed, closing this as a duplicate of #592

**Closed by BrianFarnhill** 2017-06-13 04:11 UTC
