### ISSUE TITLE
Update SPProductUpdate, SPInstall and SPInstallPrereqs to throw error when files are blocked

### ISSUE THREAD

**Issue by atear10** [PowerShell/SharePointDsc#464] opened 2016-11-25 07:13 UTC
**Details of the scenario you try and problem that is occurring:**
we are trying torun the SPProductUpdate along with SPConfigWizard module to apply SP1 on our Sharepoint 2013 Trial Version , it keeps running and doesnt stop or throw any kind of error

No of VM's : 2
Purpose : Apply SP1 on both
Source where script runs : VM1  
Target :  VM1 , VM2   

**The DSC configuration that is using the resource:**

    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName SharePointDsc
    Import-DscResource -ModuleName xWebAdministration
    Import-DscResource -ModuleName xCredSSP
    Import-DscResource -ModuleName xDisk
    node $AllNodes.NodeName
    {              
       SPProductUpdate InstallCUMay2016
        {
            SetupFile            = "D:\officeserversp2013-kb2880552-fullfile-x64-en-us.exe"
            ShutdownServices     = $false
            Ensure               = "Present"
            PsDscRunAsCredential = $FarmAccount
        }
        
       SPConfigWizard RunConfigWizard
        {
            Ensure               = "Present"
            PsDscRunAsCredential = $FarmAccount
            DependsOn            = "[SPProductUpdate]InstallCUMay2016"
        }
        
       LocalConfigurationManager
        {
            RebootNodeIfNeeded   = $true
        }
    }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 Standard RTM , Powershell 5.0 

**Version of the DSC module you're using:**
14.0.0.0

[DSC.docx](https://github.com/PowerShell/SharePointDsc/files/612679/DSC.docx)

**Comment by BrianFarnhill** [comment] 2016-11-25 07:34
@ykuijs Have you got some bandwidth to help look in to this one?

**Comment by ykuijs** [comment] 2016-11-25 12:06
Hi @atear10, I will help you figure this one out. To start of, I have a few questions:
- In the text you are saying that you are trying to install SP1, but the config shows that you are trying to install the May 2016 CU. Just to make sure we are on the same page: Exactly what are you trying to do? Does the install package have SP1 slipstreamed or is it the RTM version?
- Does the event log show any messages that relate to this issue?
- Are you trying a push or a pull config?

**Comment by atear10** [comment] 2016-11-25 13:01
Hi @ykuijs  , Sorry for the confusion , we are trying to apply the service pack 1 for SharePoint , we didn't realize that the  name given was "InstallCUMay2016" , doesn't make a difference isn't it . the actual file is still "officeserversp2013-kb2880552-fullfile-x64-en-us.exe" which is a SP1 setup file .
we are downloading the setup file from "https://www.microsoft.com/en-in/download/details.aspx?id=42544"

-The Event Log does not show any message

- It is a Push (sending the config from one node to the target node)

**Comment by ykuijs** [comment] 2016-11-25 15:12
Can you share the output the Start-DSCConfiguration command is giving? Please use the -Verbose option to run the command in Verbose mode.

**Comment by atear10** [comment] 2016-11-26 18:50
Hi @ykuijs , Below is the screenshot of the output that I am getting after start-dscconfiguration .

![image](https://cloud.githubusercontent.com/assets/17720180/20642522/f5dd26a6-b436-11e6-84bd-ccf7da54b46f.png)

**Comment by ykuijs** [comment] 2016-11-28 09:00
We will have to figure this one out, but as a workaround: A slipstreamed version of SharePoint with service pack 1 is available for download.

**Comment by ykuijs** [comment] 2016-11-28 20:10
You can find the SP2013 with SP1 slipstreamed here:
https://www.microsoft.com/en-us/download/details.aspx?id=42039

For troubleshooting:
Can you please test what happens if your run the update manually by following these steps:

1. Log in using the account you are using in the DSC config
2. Open an elevated command prompt
3. Browse to the location where the setup file is located
4. Run the command "officeserversp2013-kb2880552-fullfile-x64-en-us.exe /quiet /passive"
5. See what happens and report back the outcome

**Comment by atear10** [comment] 2016-11-29 08:29
Hi @ykuijs  , thank you for the workaround but we had already taken a call that we would go with SharePoint Server 2013 but not Foundation.

- Ran "officeserversp2013-kb2880552-fullfile-x64-en-us.exe /quiet /passive" with the account that is using DSC Config under elevated permissions , it has installed the SP1 without any errors.

**Comment by ykuijs** [comment] 2016-11-29 12:58
My apologies, didn't notice that I had shared the SPF download. The SharePoint Server 2013 with SP1 ISO is downloadable via the Volume License Service Center (VLSC) or MSDN.

When you are deploying SP1 via DSC and the install seems stuck, do you see a process "officeserversp2013-kb2880552-fullfile-x64-en-us.exe" in the Task Manager? And how much CPU time is it using?

Can you also try this:
- Log in with the account used in the config
- Open %TMP% in Explorer, the temp folder should be opened
- Delete all .log files in this location
- Restart the installation
- Check for any .log files created in the temp location

**Comment by atear10** [comment] 2016-11-29 13:25
@ykuijs I'm sorry to say there is no process "officeserversp2013-kb2880552-fullfile-x64-en-us.exe" in the Task manager during DSC fire. 
![image](https://cloud.githubusercontent.com/assets/17720180/20711270/dc7190b4-b664-11e6-9a1e-9dcb257ef3d6.png)


During the manual installation we did see the "officeserversp2013-kb2880552-fullfile-x64-en-us.exe /quiet /passive" task in task manager running in the background 

Deleted all .Log files and restarted DSC , it did not generate any log files , screenshot below for the second run
![image](https://cloud.githubusercontent.com/assets/17720180/20711377/5e52821e-b665-11e6-8ed1-76f610e3d756.png)

**Comment by ykuijs** [comment] 2016-12-01 20:25
It looks like that somehow the setup isn't started. I will have to try to reproduce this issue.

In the mean time: Do you have access to a VLSC or MSDN account to download the SharePoint Server 2013 with SP1??

**Comment by atear10** [comment] 2016-12-02 03:56
@ykuijs  Thank you :) .....eagerly waiting

our Project lead might be having an account , not sure though.

**Comment by atear10** [comment] 2016-12-07 09:59
@ykuijs Hello there ! ....just dropping by to check ,any kind of update let us know .

**Comment by ykuijs** [comment] 2016-12-07 15:19
@atear10 Sorry, have been busy the past week. Hopefully I have some time in the next few days. Have to build a new environment based on the RTM bits before I can reproduce, which takes some time.

**Comment by MikeLacher448** [comment] 2016-12-13 00:36
@atear10, when you ran the update manually, did you have to acknowledge any warning dialogs? (this file may be unsafe, etc...)

**Comment by BrianFarnhill** [comment] 2016-12-14 22:46
Just out of curiosity, is the path to officeserversp2013-kb2880552-fullfile-x64-en-us.exe on a network path or share or is it locally on the machine? I've found that if you have UAC enabled DSC will freeze like this waiting for a UAC prompt which can't ever be clicked on. Maybe have a go at disabling UAC to see if this is the issue? I found this same issue with SPInstall and SPInstallPrereqs (we just updated our guidance on these two in #473) so that's why I thought it could be related.

**Comment by MikeLacher448** [comment] 2016-12-16 23:15
I've seen where you need to run unblock-file to remove the flag that identifies it as an internet download.

**Comment by atear10** [comment] 2016-12-21 06:52
@MikeLacher448 we did not encounter any warning dialogs ...i'm sure of this 
@BrianFarnhill  the path  to officeserversp2013-kb2880552-fullfile-x64-en-us.exe is locally on the machine.. what is UAC ? it never froze for SPInstall and SPinstallPrereqs

**Comment by BrianFarnhill** [comment] 2016-12-21 21:35
@atear10 "User account control" - its that thing that makes the screen dim when you run an executable and lets you know what you are doing is about to need admin rights to do it. 

To @MikeLacher448 's point though, you might not have seen a warning prompt for his idea to be valid. But to rule out both his and my thoughts on this one, lets do a bit of a test. Can you do the following steps for me?

1. Run powershell as the account that you have set in the PsDscRunAsCredential (when powershell is open type "whoami" to be sure you get the right username back.
2. Run the following command:

    Start-Process -FilePath [[PATH TO THE UPDATE]] -Wait -PassThru

If when you run this you get any kind of error or prompt or warning, anything other than the installer opening up for you to accept the EULA like they normally do, then this is likely where the concern is. So have a go at that and let us know how that goes so we can keep troubleshooting.

**Comment by BrianFarnhill** [comment] 2017-02-01 05:04
@atear10 How did you go testing this with the suggestion I made above?

**Comment by BrianFarnhill** [comment] 2017-04-13 01:40
Given that this one hasn't been responded to since early Feb I'm closing it off. If we get more comments on it I'll re-open it to continue investigation

**Comment by Christwe** [comment] 2017-04-18 00:18
I know this was closed due to lack of response, but i hit the same problem and by unblocking the file (right click file -> Properties -> Check box to unblock) the installation ran the next time dsc checked.

**Comment by llowevad** [comment] 2017-06-20 15:14
Thank you @Christwe, unblocking the file allowed DSC to start the execution of the install.

My setup is pulling the update from a UNC path share from another computer. I checked the computer where the file is shared and the "unblock" check box was already cleared. I then went to my sharepoint server and went to the share and there was a button to "unblock" the .exe file. Which I did and now it is able to run.

Maybe the Unblock-File PS Cmdlet (https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/unblock-file) will help. I am looking to redownload and test this since I cannot "re-block" the file.

**Comment by llowevad** [comment] 2017-06-20 15:29
it is working now that I added the following to the SPProductUpdate manually

Unblock-File -Path $SetupFile

before it calls to execute the file.

![image](https://user-images.githubusercontent.com/8823690/27341567-a511b978-55ab-11e7-8816-8711b3c8661d.png)

**Comment by BrianFarnhill** [comment] 2017-06-20 17:00
@llowevad That is expected behaviour, because the blocked file will cause a UAC prompt which will sit there and never be responded to from DSC. So putting the Unblock-File prompt in will resolve that, but I don't want to make the assumption for all customers that unblocking a file is the right thing there (you're making a change to the security of the file and there is no way to re-block it after we are done) so we don't do that in our resources. That said, since this comes up from time to time we could probably have better documentation on it to help people who do hit the issue as well. So thanks for coming back to us on this one.

**Comment by ykuijs** [comment] 2017-06-20 19:28
I will update the documentation in my Rollup PR

**Comment by llowevad** [comment] 2017-06-21 14:16
@BrianFarnhill, I can understand where this would need to be something the user executing would need to determine if this is something they need to bypass. If the instructions can indicate how to resolve this to keep the level of automation that would be great (meaning not having to stop the process in order to manually unblock or disable / reconfigure UAC for a new VM). 

Another idea would be to have an option for unblock in the configuration, which defaults to $false, but the user can change to $true if it fits within their corporate policies.

**Comment by andikrueger** [comment] 2017-06-21 16:46
There is a possible way to unblock and block a file again.

1. Get the current Zone Identifier of the file:
`$zone = Get-Content <PathToFile> -Stream "Zone.Identifier"`
This might result in an ObjectNotFound Exception.

2. Unblock the file
`Unblock-File <PathToFile> -Force`

3. If there was a lock:
`Set-Content <PathToFile> -Stream "Zone.Identifier" -Value $zone`

**Comment by ykuijs** [comment] 2017-06-22 10:41
I would like to suggest the following:
To prevent the resource from entering the endless wait state, we can add a check if a file is blocked. If that is the case, throw an error specifying that the file needs to be unblocked before continuing. That way the blocked file won't block the installation. Would this be an idea?

**Comment by BrianFarnhill** [comment] 2017-06-22 14:34
I agree with @ykuijs - I would much rather give a meaningful error to avoid the hang than to make the security changes to the file and execute them. I'll re-open the issue so we can track getting that change made.

**Comment by ykuijs** [comment] 2017-06-24 11:34
Check is added in my next Rollup PR

**Comment by BrianFarnhill** [comment] 2017-07-02 22:36
This has been rolled in to dev and will be included in our next release. Closing this issue.

**Closed by BrianFarnhill** 2017-07-02 22:36 UTC
Labels: bug, in progress
