### ISSUE TITLE
SPFarm: crash wsmprovhost.exe after now joining to farm at server

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#860] opened 2018-08-30 12:38 UTC
#### Details of the scenario you tried and the problem that is occurring
Try SPFarm resource but it crash wsmprovhost.exe after "now joining to farm at server" (command New-SPConfigurationDatabase)
It's seems not working on remote session!

#### Verbose logs showing the problem
VERBOSE: [Win19SP19Prview]:                            [[SPFarm]DirectResourceAccess] Now joining to farm at server Win19SP19Prv
iew database SP_Config
VERBOSE: [Win19SP19Prview]: LCM:  [ End    Set      ]  [[SPFarm]DirectResourceAccess]  in 374.1140 seconds.
PowerShell DSC resource MSFT_SPFarm  failed to execute Set-TargetResource functionality with error message: Processing data 
from remote server localhost failed with the following error message: The WSMan provider host process did not return a proper 
response.  A provider in the host process may have behaved improperly. For more information, see the 
about_Remote_Troubleshooting Help topic. 
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.

In event viewer:
Faulting application name: wsmprovhost.exe, version: 10.0.17666.1000, time stamp: 0x5241da4a
Faulting module name: ntdll.dll, version: 10.0.17666.1000, time stamp: 0x2b6f1d68
Exception code: 0xc0000409
Fault offset: 0x0000000000089dbf
Faulting process id: 0xb20
Faulting application start time: 0x01d4404c2d69de51
Faulting application path: C:\Windows\system32\wsmprovhost.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 47cfaa49-3a19-4c3f-a209-ff7d9d3d92f1
Faulting package full name: 
Faulting package-relative application ID: 

#### Suggested solution to the issue
Work only if I invoke the command directly on local server:
New-SPConfigurationDatabase -DatabaseName SP_Config -DatabaseServer sqlsp -LocalServerRole SingleServerFarm -AdministrationContentDatabaseName SP_CentralAdmin -FarmCredentials $Credfarm -Passphrase (New-Object System.Management.Automation.PSCredential ('Passphrase', (ConvertTo-SecureString "Sharepoint2019" -AsPlainText -Force))).Password -Verbose

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
 IsSingleInstance = "Yes"
                Passphrase = New-Object System.Management.Automation.PSCredential ('Passphrase', (ConvertTo-SecureString "Sharepoint2019" -AsPlainText -Force));
                AdminContentDatabaseName = "SP_CentralAdmin";
                FarmConfigDatabaseName = "SP_Config";
                FarmAccount = $Cred_farm;
                CentralAdministrationPort = 4715;
                PsDscRunAsCredential = $Cred_admin
                CentralAdministrationAuth = "NTLM";
                RunCentralAdmin = $True;
              ServerRole = "SingleServerFarm"
                Ensure = "Present";
                DatabaseServer = "Win19SP19Prview";

#### The operating system the target node is running
OsName               : Microsoft Windows Server Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1803
WindowsBuildLabEx    : 17666.1000.amd64fre.rs_prerelease.180504-1501
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running                                                                                      
PSVersion                      5.1.17666.1000                                                                                  
PSEdition                      Desktop                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                         
BuildVersion                   10.0.17666.1000                                                                                 
CLRVersion                     4.0.30319.42000                                                                                 
WSManStackVersion              3.0                                                                                             
PSRemotingProtocolVersion      2.3                                                                                             
SerializationVersion           1.1.0.1    

#### Version of the DSC module that was used ('dev' if using current dev branch)
v3.0-development

**Comment by ykuijs** [comment] 2018-08-30 14:13
Hi @paololec What do you mean with "It's seems not working on remote session!"? 

Does this mean you tried to run the New-SPConfigurationDatabase cmdlets via PowerShell remoting and that did not work either?

**Comment by paololec** [comment] 2018-08-30 14:39
Yes, same command to reproduce the bug using a "New-PSSession" to simulate the DSC:
`
$Credssp_admin = New-Object System.Management.Automation.PSCredential("domainName\spadmin", ("SPpassword19!" | ConvertTo-SecureString -asPlainText -Force))
$s = New-PSSession -ComputerName $env:COMPUTERNAME -Credential $Credssp_admin -Authentication Credssp -SessionOption (New-PSSessionOption -OperationTimeout 0 -IdleTimeout 600000)
$result = Invoke-Command -Session $s -Scriptblock {
Add-PSSnapin Microsoft.SharePoint.PowerShell
$Credssp_farm = New-Object System.Management.Automation.PSCredential("domainName\spfarm", ("SharePoint2019!" | ConvertTo-SecureString -asPlainText -Force))

New-SPConfigurationDatabase -DatabaseName SP_Config -DatabaseServer sqlsp -LocalServerRole SingleServerFarm -AdministrationContentDatabaseName SP_CentralAdmin -FarmCredentials $Credssp_farm -Passphrase (New-Object System.Management.Automation.PSCredential ('Passphrase', (ConvertTo-SecureString "Sharepoint2019" -AsPlainText -Force))).Password -Verbose
}
Remove-PSSession $s
`


The error:
VERBOSE: Now joining to farm at server sqlsp database SP_Config
Processing data for a remote command failed with the following error message: The WSMan provider host process did not return a 
proper response.  A provider in the host process may have behaved improperly. For more information, see the 
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (Win19SP19Prview:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : Win19SP19Prview

**Comment by ykuijs** [comment] 2018-08-31 08:17
In that case it doesn't look related to SharePointDsc, but is an issue with SharePoint 2019. Did you already report it in the SP2019 support forum?
https://social.technet.microsoft.com/Forums/office/en-US/home?forum=SP2019

**Comment by ykuijs** [comment] 2018-08-31 09:37
What build of Windows Server are you using? Build 10.0.17666 isn't 1803, which is build 10.0.17314: https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info

**Comment by ykuijs** [comment] 2018-09-04 12:29
This indeed sounds like a OS issue. Did you already report it in the SP2019 forum?

And can you please try to reproduce on a Windows Server 2016 environment?

**Comment by paololec** [comment] 2018-09-11 10:19
I try on Windows Server 2016 and it work fine. The bug is only on "windows server 2019 preview"

**Comment by ykuijs** [comment] 2018-10-05 10:57
Closing this issue since it is not SharePointDsc related

**Closed by ykuijs** 2018-10-05 10:57 UTC
Labels: external, needs investigation
