### ISSUE TITLE
SPinstall : The parameter is incorrect

### ISSUE THREAD

**Issue by JeanNetryValere** [PowerShell/SharePointDsc#1058] opened 2019-04-18 09:36 UTC
#### Details of the scenario you tried and the problem that is occurring
Hello,
I had an issue installing SharePoint 2019 binairies with no observable reason.
My configuration was working fine on same environement build with 3.2.0.0. Doing the switch to 3.3.0.0 raise the following exception.
Forcing the same back to 3.2.0.0 avoid the exception and continue the installation succesfully. 
Didn't found why, so here the problem.

#### Verbose logs showing the problem
VERBOSE: [GVAXXXXXXD]: LCM:  [ Start  Resource ]  [[SPInstall]InstallSharePoint]
VERBOSE: [GVAXXXXXXD]: LCM:  [ Start  Test     ]  [[SPInstall]InstallSharePoint]
VERBOSE: [GVAXXXXXXD]:                            [[SPInstall]InstallSharePoint] Importing the module MSFT_SPInstall in force mode.
VERBOSE: [GVAXXXXXXD]:                            [[SPInstall]InstallSharePoint] Importing the module MSFT_SPInstall in force mode.
VERBOSE: [GVAXXXXXXD]:                            [[SPInstall]InstallSharePoint] Testing install status of SharePoint
VERBOSE: [GVAXXXXXXD]:                            [[SPInstall]InstallSharePoint] Getting install status of SharePoint
VERBOSE: [GVAXXXXXXD]:                            [[SPInstall]InstallSharePoint] Checking file status of V:\setup.exe
The parameter is incorrect
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.GetItemCommand
    + PSComputerName        : gvaxxxx.gva.xxxx.priv
 
VERBOSE: [GVAXXXXXXD]: LCM:  [ End    Test     ]  [[SPInstall]InstallSharePoint]  in 0.9060 seconds.
The PowerShell DSC resource '[SPInstall]InstallSharePoint' with SourceInfo '::96::9::SPInstall' threw one or more non-terminating errors while running the Test-TargetResource 
functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : gvaxxxx.gva.xxxx.priv
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

SPInstall InstallSharePoint {
            Ensure                  = 'Present'
            IsSingleInstance        = 'Yes'
            BinaryDir               = 'V:\'
            ProductKey              = $ConfigurationData.NonNodeData.SharePoint.ProductKey
            DependsOn               = '[SPInstallPrereqs]InstallPrereqs'
        }

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2848.amd64fre.rs1_release.190305-1856
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019 Enterprise

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.3.0.0

**Comment by ykuijs** [comment] 2019-04-23 12:11
v3.3 added a check that validates that the setup file is not blocked and causing the resource to hang in an endless loop, waiting for confirmation of a security message. Somehow this check fails in your case. Can you please run the following command:
```PowerShell
Get-Item "V:\setup.exe" -Stream "Zone.Identifier"
```

Also a question: Is the V-drive a mapped network drive? If so, have you tried to use the UNC notation (\\server\share) instead of the mapped drive?

**Comment by JeanNetryValere** [comment] 2019-04-24 06:51
Hello,
Same error raised by the DSC Ressource (see below)
The "V" Drive is an iso previously mounted by a MountImage ressource (available and accessible for the install account).

PS C:\Users\a_jnetryvalere> Get-Item "V:\setup.exe" -Stream "Zone.Identifier"
Get-Item : The parameter is incorrect
At line:1 char:1
+ Get-Item "V:\setup.exe" -Stream "Zone.Identifier"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.GetItemCommand

**Comment by ykuijs** [comment] 2019-04-24 07:59
Just tested this and can confirm this is caused by the fact that this occurs on a mounted disk image. Not sure why this is happening though. We will have to investigate the cause.

**Comment by ykuijs** [comment] 2019-04-24 13:10
@JeanNetryValere can you please run the following script to test if this works in your case:
```PowerShell
$drive = Get-Volume -DriveLetter V -ErrorAction SilentlyContinue
if ($null -ne $drive)
{
    if ($drive.DriveType -ne "CD-ROM")
    {
        Write-Output "Drive: Perform test"
    }
    else
    {
        Write-Output "CD-ROM: Skip test"
    }
}
else
{
    Write-Output "Drive not found: ERROR!"
}
```

**Comment by JeanNetryValere** [comment] 2019-04-24 14:34
No mistakes, the output is:
"CD-ROM: Skip test"

**Comment by ykuijs** [comment] 2019-04-24 18:41
Great! Implementing a fix for this issue, which will be included in my next Bugfix PR

**Closed** 2019-05-06 13:17 UTC
Labels: bug, in progress
